### ISSUE TITLE
colliders???

### ISSUE THREAD

**Issue by huhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuh** [nerk987/RigFlex#4]
So im trying to figure out if colliders work with this? but i cant seem to get them to and i cant find anything online about it, so if someone could help. that would be heplful!

**Comment by nerk987** [comment]
Sorry, no colliders available, and none planned. The intention is to keep it very simple and stable. Checkout the Wiggle-bones add-on. It does a lot more, but is harder to get right.
