### ISSUE TITLE
Workflow question.

### ISSUE THREAD

**Issue by cgdive-todor** [nerk987/RigFlex#5]
Hi,
I tested the addon and it seems to work except that I don't seem to understand the full process. I can bake the bones that I want to get "flexy". That creates new bones with soft body effect. But ultimately I want the soft body to be applied to my original bones, right? At least that makes sense to me. I can do it by constraining the original bones to the flex bones and baking them but since I don't see an automation for that in the addon, I think that is not what the addon intends. So I am just trying to understand the intended workflow.

Also what does the Initialize button do?

Thanks!

**Comment by nerk987** [comment]
Actually, at least for my workflow, I don't want the original bones to be modified. I just want a new 'layer' of flexiness to be added (and then modifed or removed if required). The add-on automatically modifies the vertex groups of any meshes that are using the armature for deformation to point at the 'flexy' layer of bones, and will restore the original groups if you prefer.

The Initialize button adds the stiffness value to the selected bones. The Bake button also does this, so you really only need the Initialize function to add different values of stiffness to different bones.
